title: Kai Zhao
# tagline: Here is personal website of Hanlin Cai. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://zkManuel0123.github.io

# Owner/author information
owner:
  name: Kai Zhao
  avatar: /kaizhao.jpg
  # bio: Two roads diverged in woods, I took the one less traveled by.
  email: kai.zhao@stud.tu-darmstadt.de
  cv: https://zkManuel0123.github.io/file/CV-KaiZhao_20240928.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: zkManuel0123
  linkedin: http://www.linkedin.com/in/kai-zhao-manuel0123
  #scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  #researchgate: https://www.researchgate.net/profile/Hanlin-Cai

  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /

  - title: Work Experiences
    url: /awards/
  - title: Projects
    url: /blogs/
  - title: Hobbies
    url: /hobbies/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Berlin
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude:
  [
    "lib",
    "config.rb",
    "Capfile",
    "config",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "minimal-mistakes.sublime-project",
    "minimal-mistakes.sublime-workspace",
  ]
# Latest update in 2023/12/10 by Hanlin Cai.
